apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: ocp-demo
spec:
  serviceAccountName: demo-nube
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest  # Usamos la imagen oficial de Apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-content
              mountPath: /usr/local/apache2/htdocs  # Ruta estándar para contenido web de Apache
      volumes:
        - name: apache-content
          emptyDir: {}
          
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: ocp-demo
spec:
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apache-route
  namespace: ocp-demo
spec:
  to:
    kind: Service
    name: apache-service
  port:
    targetPort: 80
