apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: ocp-demo
spec:
  serviceAccountName: demo-nube
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: registry.redhat.io/ubi9/httpd-24:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-content
              mountPath: /usr/share/httpd/noindex.html  # Apache default index file location
      volumes:
        - name: apache-content
          emptyDir: {}  # Temporary empty directory if necessary for the files   
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: ocp-demo
spec:
  selector:
    app: apache
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apache-route
  namespace: ocp-demo
spec:
  to:
    kind: Service
    name: apache-service
  port:
    targetPort: 8080
