apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-adm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipelinerun-access
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelinerun-access-binding
subjects:
  - kind: ServiceAccount
    name: tekton-adm
    namespace: ocp-demo
roleRef:
  kind: ClusterRole
  name: tekton-pipelinerun-access
  apiGroup: rbac.authorization.k8s.io
