apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-demo
  namespace: ocp-demo
spec:
  params:
    - name: gitrepositoryurl
      description: The git repository url
    - name: message
      description: The message to print
      default: This is the default message
    - name: contenttype
      description: The Content-Type of the event
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-demo
      spec:
        params:
          - name: repo-url
            value: "$(params.gitrepositoryurl)"
        pipelineRef:
          name: pipeline-demo
        workspaces:
          - name: workspace-git
            persistentVolumeClaim:
              claimName: pvc-git-pipeline
