apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-git-demo
spec:
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
